{@html `<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Unity WebGL Player | Slash Hero</title>
    <link rel="shortcut icon" href="/game/Slash/TemplateData/favicon.ico">
    <link rel="stylesheet" href="/game/Slash/TemplateData/style.css">
  </head>
  <body>
    <div id="unity-container" class="unity-desktop">
      <canvas id="unity-canvas" width=960 height=600></canvas>
      <div id="unity-loading-bar">
        <div id="unity-logo"></div>
        <div id="unity-progress-bar-empty">
          <div id="unity-progress-bar-full"></div>
        </div>
      </div>
      <div id="unity-warning"> </div>
      <div id="unity-footer">
        <div id="unity-webgl-logo"></div>
        <div id="unity-fullscreen-button"></div>
        <div id="unity-build-title">Slash Hero</div>
      </div>
    </div>
    <script ✂prettier:content✂="CiAgICAgIHZhciBjb250YWluZXIgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCIjdW5pdHktY29udGFpbmVyIik7CiAgICAgIHZhciBjYW52YXMgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCIjdW5pdHktY2FudmFzIik7CiAgICAgIHZhciBsb2FkaW5nQmFyID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcigiI3VuaXR5LWxvYWRpbmctYmFyIik7CiAgICAgIHZhciBwcm9ncmVzc0JhckZ1bGwgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCIjdW5pdHktcHJvZ3Jlc3MtYmFyLWZ1bGwiKTsKICAgICAgdmFyIGZ1bGxzY3JlZW5CdXR0b24gPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCIjdW5pdHktZnVsbHNjcmVlbi1idXR0b24iKTsKICAgICAgdmFyIHdhcm5pbmdCYW5uZXIgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCIjdW5pdHktd2FybmluZyIpOwoKICAgICAgLy8gU2hvd3MgYSB0ZW1wb3JhcnkgbWVzc2FnZSBiYW5uZXIvcmliYm9uIGZvciBhIGZldyBzZWNvbmRzLCBvcgogICAgICAvLyBhIHBlcm1hbmVudCBlcnJvciBtZXNzYWdlIG9uIHRvcCBvZiB0aGUgY2FudmFzIGlmIHR5cGU9PSdlcnJvcicuCiAgICAgIC8vIElmIHR5cGU9PSd3YXJuaW5nJywgYSB5ZWxsb3cgaGlnaGxpZ2h0IGNvbG9yIGlzIHVzZWQuCiAgICAgIC8vIE1vZGlmeSBvciByZW1vdmUgdGhpcyBmdW5jdGlvbiB0byBjdXN0b21pemUgdGhlIHZpc3VhbGx5IHByZXNlbnRlZAogICAgICAvLyB3YXkgdGhhdCBub24tY3JpdGljYWwgd2FybmluZ3MgYW5kIGVycm9yIG1lc3NhZ2VzIGFyZSBwcmVzZW50ZWQgdG8gdGhlCiAgICAgIC8vIHVzZXIuCiAgICAgIGZ1bmN0aW9uIHVuaXR5U2hvd0Jhbm5lcihtc2csIHR5cGUpIHsKICAgICAgICBmdW5jdGlvbiB1cGRhdGVCYW5uZXJWaXNpYmlsaXR5KCkgewogICAgICAgICAgd2FybmluZ0Jhbm5lci5zdHlsZS5kaXNwbGF5ID0gd2FybmluZ0Jhbm5lci5jaGlsZHJlbi5sZW5ndGggPyAnYmxvY2snIDogJ25vbmUnOwogICAgICAgIH0KICAgICAgICB2YXIgZGl2ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnZGl2Jyk7CiAgICAgICAgZGl2LmlubmVySFRNTCA9IG1zZzsKICAgICAgICB3YXJuaW5nQmFubmVyLmFwcGVuZENoaWxkKGRpdik7CiAgICAgICAgaWYgKHR5cGUgPT0gJ2Vycm9yJykgZGl2LnN0eWxlID0gJ2JhY2tncm91bmQ6IHJlZDsgcGFkZGluZzogMTBweDsnOwogICAgICAgIGVsc2UgewogICAgICAgICAgaWYgKHR5cGUgPT0gJ3dhcm5pbmcnKSBkaXYuc3R5bGUgPSAnYmFja2dyb3VuZDogeWVsbG93OyBwYWRkaW5nOiAxMHB4Oyc7CiAgICAgICAgICBzZXRUaW1lb3V0KGZ1bmN0aW9uKCkgewogICAgICAgICAgICB3YXJuaW5nQmFubmVyLnJlbW92ZUNoaWxkKGRpdik7CiAgICAgICAgICAgIHVwZGF0ZUJhbm5lclZpc2liaWxpdHkoKTsKICAgICAgICAgIH0sIDUwMDApOwogICAgICAgIH0KICAgICAgICB1cGRhdGVCYW5uZXJWaXNpYmlsaXR5KCk7CiAgICAgIH0KCiAgICAgIHZhciBidWlsZFVybCA9ICIvZ2FtZS9TbGFzaC9CdWlsZCI7CiAgICAgIHZhciBsb2FkZXJVcmwgPSBidWlsZFVybCArICIvd2ViR0wubG9hZGVyLmpzIjsKICAgICAgdmFyIGNvbmZpZyA9IHsKICAgICAgICBkYXRhVXJsOiBidWlsZFVybCArICIvd2ViR0wuZGF0YSIsCiAgICAgICAgZnJhbWV3b3JrVXJsOiBidWlsZFVybCArICIvd2ViR0wuZnJhbWV3b3JrLmpzIiwKICAgICAgICBjb2RlVXJsOiBidWlsZFVybCArICIvd2ViR0wud2FzbSIsCiAgICAgICAgc3RyZWFtaW5nQXNzZXRzVXJsOiAiU3RyZWFtaW5nQXNzZXRzIiwKICAgICAgICBjb21wYW55TmFtZTogIkRlZmF1bHRDb21wYW55IiwKICAgICAgICBwcm9kdWN0TmFtZTogIlNsYXNoIEhlcm8iLAogICAgICAgIHByb2R1Y3RWZXJzaW9uOiAiMS4wIiwKICAgICAgICBzaG93QmFubmVyOiB1bml0eVNob3dCYW5uZXIsCiAgICAgIH07CgogICAgICAvLyBCeSBkZWZhdWx0IFVuaXR5IGtlZXBzIFdlYkdMIGNhbnZhcyByZW5kZXIgdGFyZ2V0IHNpemUgbWF0Y2hlZCB3aXRoCiAgICAgIC8vIHRoZSBET00gc2l6ZSBvZiB0aGUgY2FudmFzIGVsZW1lbnQgKHNjYWxlZCBieSB3aW5kb3cuZGV2aWNlUGl4ZWxSYXRpbykKICAgICAgLy8gU2V0IHRoaXMgdG8gZmFsc2UgaWYgeW91IHdhbnQgdG8gZGVjb3VwbGUgdGhpcyBzeW5jaHJvbml6YXRpb24gZnJvbQogICAgICAvLyBoYXBwZW5pbmcgaW5zaWRlIHRoZSBlbmdpbmUsIGFuZCB5b3Ugd291bGQgaW5zdGVhZCBsaWtlIHRvIHNpemUgdXAKICAgICAgLy8gdGhlIGNhbnZhcyBET00gc2l6ZSBhbmQgV2ViR0wgcmVuZGVyIHRhcmdldCBzaXplcyB5b3Vyc2VsZi4KICAgICAgLy8gY29uZmlnLm1hdGNoV2ViR0xUb0NhbnZhc1NpemUgPSBmYWxzZTsKCiAgICAgIGlmICgvaVBob25lfGlQYWR8aVBvZHxBbmRyb2lkL2kudGVzdChuYXZpZ2F0b3IudXNlckFnZW50KSkgewogICAgICAgIGNvbnRhaW5lci5jbGFzc05hbWUgPSAidW5pdHktbW9iaWxlIjsKICAgICAgICAvLyBBdm9pZCBkcmFpbmluZyBmaWxscmF0ZSBwZXJmb3JtYW5jZSBvbiBtb2JpbGUgZGV2aWNlcywKICAgICAgICAvLyBhbmQgZGVmYXVsdC9vdmVycmlkZSBsb3cgRFBJIG1vZGUgb24gbW9iaWxlIGJyb3dzZXJzLgogICAgICAgIGNvbmZpZy5kZXZpY2VQaXhlbFJhdGlvID0gMTsKICAgICAgICB1bml0eVNob3dCYW5uZXIoJ1dlYkdMIGJ1aWxkcyBhcmUgbm90IHN1cHBvcnRlZCBvbiBtb2JpbGUgZGV2aWNlcy4nKTsKICAgICAgfSBlbHNlIHsKICAgICAgICBjYW52YXMuc3R5bGUud2lkdGggPSAiOTYwcHgiOwogICAgICAgIGNhbnZhcy5zdHlsZS5oZWlnaHQgPSAiNjAwcHgiOwogICAgICB9CiAgICAgIGxvYWRpbmdCYXIuc3R5bGUuZGlzcGxheSA9ICJibG9jayI7CgogICAgICB2YXIgc2NyaXB0ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgic2NyaXB0Iik7CiAgICAgIHNjcmlwdC5zcmMgPSBsb2FkZXJVcmw7CiAgICAgIHNjcmlwdC5vbmxvYWQgPSAoKSA9PiB7CiAgICAgICAgY3JlYXRlVW5pdHlJbnN0YW5jZShjYW52YXMsIGNvbmZpZywgKHByb2dyZXNzKSA9PiB7CiAgICAgICAgICBwcm9ncmVzc0JhckZ1bGwuc3R5bGUud2lkdGggPSAxMDAgKiBwcm9ncmVzcyArICIlIjsKICAgICAgICB9KS50aGVuKCh1bml0eUluc3RhbmNlKSA9PiB7CiAgICAgICAgICBsb2FkaW5nQmFyLnN0eWxlLmRpc3BsYXkgPSAibm9uZSI7CiAgICAgICAgICBmdWxsc2NyZWVuQnV0dG9uLm9uY2xpY2sgPSAoKSA9PiB7CiAgICAgICAgICAgIHVuaXR5SW5zdGFuY2UuU2V0RnVsbHNjcmVlbigxKTsKICAgICAgICAgIH07CiAgICAgICAgfSkuY2F0Y2goKG1lc3NhZ2UpID0+IHsKICAgICAgICAgIGFsZXJ0KG1lc3NhZ2UpOwogICAgICAgIH0pOwogICAgICB9OwogICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKHNjcmlwdCk7CiAgICA=" ✂prettier:content✂="e30=" ✂prettier:content✂="e30=">{}</script>
  </body>
</html>`}
