root: true
parser: "@typescript-eslint/parser"
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:svelte/recommended
    - plugin:svelte/prettier
plugins: ["@typescript-eslint"]
env:
    es2022: true
    browser: true
    node: true
parserOptions:
    sourceType: "module"
    ecmaVersion: latest
    extraFileExtensions: [".svelte"]
overrides:
    - files: ["*.svelte"]
      parser: svelte-eslint-parser
      parserOptions:
          parser: "@typescript-eslint/parser"
