extends:
    - stylelint-config-recommended-scss
    - stylelint-config-html/svelte
rules:
    scss/at-rule-no-unknown: [true, { ignoreAtRules: ["tailwind", "apply"] }]
    scss/at-extend-no-missing-placeholder: null
